### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by ijackwu** [king6cong/react-native-ijkplayer#7]
```

D:\code\react-native-ijkplayer\Example>npm install

> bufferutil@1.2.1 install D:\code\react-native-ijkplayer\Example\node_modules\b
ufferutil
> node-gyp rebuild


D:\code\react-native-ijkplayer\Example\node_modules\bufferutil>if not defined np
m_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules
\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  e
lse (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB1025: 运行 MSBuild 时发生内部错误。
Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException: 没有为 ToolsVersi
on“14.0”(在“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0
”处定义)指定 MSBuildToolsPath，或者指定值的计算结果为空字符串。
   在 Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException.Throw(Except
ion innerException, String resourceName, Object[] args)
   在 Microsoft.Build.BuildEngine.ToolsetReader.ReadToolset(PropertyDefinition t
oolsVersion, BuildPropertyGroup globalProperties, BuildPropertyGroup initialProp
erties, Boolean accumulateProperties)
   在 Microsoft.Build.BuildEngine.ToolsetReader.ReadEachToolset(ToolsetCollectio
n toolsets, BuildPropertyGroup globalProperties, BuildPropertyGroup initialPrope
rties, Boolean accumulateProperties)
   在 Microsoft.Build.BuildEngine.ToolsetReader.ReadToolsets(ToolsetCollection t
oolsets, BuildPropertyGroup globalProperties, BuildPropertyGroup initialProperti
es, Boolean accumulateProperties)
   在 Microsoft.Build.BuildEngine.ToolsetReader.ReadAllToolsets(ToolsetCollectio
n toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader con
figurationReader, BuildPropertyGroup globalProperties, BuildPropertyGroup initia
lProperties, ToolsetDefinitionLocations locations)
   在 Microsoft.Build.BuildEngine.Engine.PopulateToolsetStateMap(ToolsetDefiniti
onLocations locations)
   在 Microsoft.Build.BuildEngine.Engine..ctor(Int32 numberOfCpus, Boolean isChi
ldNode, Int32 parentNodeId, String localNodeProviderParameters, BuildPropertyGro
up globalProperties, ToolsetDefinitionLocations locations)
   在 Microsoft.Build.BuildEngine.Engine.get_GlobalEngine()
   在 Microsoft.Build.BuildEngine.Project..ctor(Engine engine, String toolsVersi
on)
   在 Microsoft.Build.BuildEngine.SolutionWrapperProject.Generate(String solutio
nPath, String toolsVersionOverride, BuildEventContext projectBuildEventContext)
   在 Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapperUsingOldO
M(String projectFile, IDictionary`2 globalProperties, String toolsVersion, Proje
ctRootElementCache projectRootElementCache, BuildParameters buildParameters, ILo
ggingService loggingService, BuildEventContext projectBuildEventContext, Boolean
 isExplicitlyLoaded)
   在 Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String proj
ectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, Bu
ildParameters buildParameters, ILoggingService loggingService, BuildEventContext
 projectBuildEventContext, Boolean isExplicitlyLoaded)
   在 Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(Build
RequestConfiguration config, BuildEventContext buildEventContext)
   在 Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildR
equestBlocker blocker)
   在 Microsoft.Build.Execution.BuildManager.IssueRequestToScheduler(BuildSubmis
sion submission, Boolean allowMainThreadBuild, BuildRequestBlocker blocker)
   在 Microsoft.Build.Execution.BuildManager.<>c__DisplayClass60_1.<ExecuteSubmi
ssion>b__0()

MSBUILD : error MSB1025: 运行 MSBuild 时发生内部错误。
Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException: 没有为 ToolsVersi
on“14.0”(在“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0
”处定义)指定 MSBuildToolsPath，或者指定值的计算结果为空字符串。
   在 Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, St
ring[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] lo
ggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRec
ords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean
enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailed
Summary)
   在 Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

未经处理的异常:  Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException:
没有为 ToolsVersion“14.0”(在“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\To
olsVersions\14.0”处定义)指定 MSBuildToolsPath，或者指定值的计算结果为空字符串。

   在 Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, St
ring[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] lo
ggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRec
ords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean
enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailed
Summary)
   在 Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   在 Microsoft.Build.CommandLine.MSBuildApp.Main()
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 3762504530
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
g\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator
\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gy
p.js" "rebuild"
gyp ERR! cwd D:\code\react-native-ijkplayer\Example\node_modules\bufferutil
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> utf-8-validate@1.2.2 install D:\code\react-native-ijkplayer\Example\node_modul
es\utf-8-validate
> node-gyp rebuild


D:\code\react-native-ijkplayer\Example\node_modules\utf-8-validate>if not define
d npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\npm\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
)  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB1025: 运行 MSBuild 时发生内部错误。
Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException: 没有为 ToolsVersi
on“14.0”(在“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0
”处定义)指定 MSBuildToolsPath，或者指定值的计算结果为空字符串。
   在 Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException.Throw(Except
ion innerException, String resourceName, Object[] args)
   在 Microsoft.Build.BuildEngine.ToolsetReader.ReadToolset(PropertyDefinition t
oolsVersion, BuildPropertyGroup globalProperties, BuildPropertyGroup initialProp
erties, Boolean accumulateProperties)
   在 Microsoft.Build.BuildEngine.ToolsetReader.ReadEachToolset(ToolsetCollectio
n toolsets, BuildPropertyGroup globalProperties, BuildPropertyGroup initialPrope
rties, Boolean accumulateProperties)
   在 Microsoft.Build.BuildEngine.ToolsetReader.ReadToolsets(ToolsetCollection t
oolsets, BuildPropertyGroup globalProperties, BuildPropertyGroup initialProperti
es, Boolean accumulateProperties)
   在 Microsoft.Build.BuildEngine.ToolsetReader.ReadAllToolsets(ToolsetCollectio
n toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader con
figurationReader, BuildPropertyGroup globalProperties, BuildPropertyGroup initia
lProperties, ToolsetDefinitionLocations locations)
   在 Microsoft.Build.BuildEngine.Engine.PopulateToolsetStateMap(ToolsetDefiniti
onLocations locations)
   在 Microsoft.Build.BuildEngine.Engine..ctor(Int32 numberOfCpus, Boolean isChi
ldNode, Int32 parentNodeId, String localNodeProviderParameters, BuildPropertyGro
up globalProperties, ToolsetDefinitionLocations locations)
   在 Microsoft.Build.BuildEngine.Engine.get_GlobalEngine()
   在 Microsoft.Build.BuildEngine.Project..ctor(Engine engine, String toolsVersi
on)
   在 Microsoft.Build.BuildEngine.SolutionWrapperProject.Generate(String solutio
nPath, String toolsVersionOverride, BuildEventContext projectBuildEventContext)
   在 Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapperUsingOldO
M(String projectFile, IDictionary`2 globalProperties, String toolsVersion, Proje
ctRootElementCache projectRootElementCache, BuildParameters buildParameters, ILo
ggingService loggingService, BuildEventContext projectBuildEventContext, Boolean
 isExplicitlyLoaded)
   在 Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String proj
ectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, Bu
ildParameters buildParameters, ILoggingService loggingService, BuildEventContext
 projectBuildEventContext, Boolean isExplicitlyLoaded)
   在 Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(Build
RequestConfiguration config, BuildEventContext buildEventContext)
   在 Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildR
equestBlocker blocker)
   在 Microsoft.Build.Execution.BuildManager.IssueRequestToScheduler(BuildSubmis
sion submission, Boolean allowMainThreadBuild, BuildRequestBlocker blocker)
   在 Microsoft.Build.Execution.BuildManager.<>c__DisplayClass60_1.<ExecuteSubmi
ssion>b__0()

MSBUILD : error MSB1025: 运行 MSBuild 时发生内部错误。
Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException: 没有为 ToolsVersi
on“14.0”(在“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0
”处定义)指定 MSBuildToolsPath，或者指定值的计算结果为空字符串。
   在 Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, St
ring[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] lo
ggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRec
ords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean
enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailed
Summary)
   在 Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

未经处理的异常:  Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException:
没有为 ToolsVersion“14.0”(在“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\To
olsVersions\14.0”处定义)指定 MSBuildToolsPath，或者指定值的计算结果为空字符串。

   在 Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, St
ring[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] lo
ggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRec
ords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean
enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailed
Summary)
   在 Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   在 Microsoft.Build.CommandLine.MSBuildApp.Main()
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 3762504530
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
g\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator
\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gy
p.js" "rebuild"
gyp ERR! cwd D:\code\react-native-ijkplayer\Example\node_modules\utf-8-validate
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\b
ufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-
gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modul
es\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `n
ode-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 119 packages in 25.976s
```

**Comment by calcyu** [comment]
我也有同样的问题，请问你修复了吗
